import type { NextPage } from "next";
import Head from "next/head";
import Header from "../components/Header";
import Loader from "../components/Loader";
import About from "../components/Sections/About";
import Hero from "../components/Sections/Hero";

const Home: NextPage = () => {
	return (
		<>
			<Loader />
			<Head>
				<title>Nat | Portfolio</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Header />
			<main>
				<Hero />
				<About />
			</main>

			<footer></footer>
		</>
	);
};

export default Home;
