import type { NextPage } from "next";
import Head from "next/head";
import Footer from "../components/Footer";
import Header from "../components/Header";
import Loader from "../components/Loader";
import About from "../components/Sections/About";
import Hero from "../components/Sections/Hero";
import Skills from "../components/Sections/Skills";
import Work from "../components/Sections/Work";

const Home: NextPage = () => {
	return (
		<>
			<Loader />
			<Head>
				<title>Nat | Portfolio</title>
				<meta name="description" content="Generated by create next app" />
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1.0"
				></meta>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Header />
			<main>
				<Hero />
				<About />
				<Skills />
				<Work />
			</main>
			<Footer />
		</>
	);
};

export default Home;
